import React from 'react';
import { Breadcrumb } from './Breadcrumb';
import Head from 'next/head'
import { CartList } from './CartList';
const Cart = () => {
    return (
        <div className='bg-[#FAF7F2]'>
            <Head>
                <title>Cart Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet" />
            </Head>
            <main>
                <Breadcrumb />
                <CartList />
            </main>
        </div>
    );
};

export default Cart;