import Head from 'next/head'
import React from 'react';

// import Image from 'next/image'
import { Footer } from '../../components/Footer/Footer';
// import { Footer } from '../components/Footer/Footer'
// import { HomeMain } from '../components/Home/HomeMain'
// import { Navbar } from '../components/Navabar/Navbar'
import { Navbar } from '../../components/Navabar/Navbar';
// import styles from '../styles/Home.module.css'

export default function index() {
    return (
        <div >
            <Head>
                <title>Food Court</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="3_003.png" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet" />
            </Head>
            <main>
                <Navbar> </Navbar>
                <p> kaj kore </p>
                <Footer></Footer>

            </main>


        </div>
    )
}







// import React from 'react';

// const index = () => {
//     return (
//         <div>
//             <p> kaj kore </p>
//         </div>
//     );
// };

// export default index;