import Head from 'next/head'
import { HomeMain } from '../components/Home/HomeMain'
import { Navbar } from '../components/Navabar/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
<<<<<<< HEAD
      <i className='text-center text-4xl font-bold'> Team Work food court </i>
=======
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar> </Navbar>
        <HomeMain> </HomeMain>
        
      </main>

>>>>>>> main
    </div>
  )
}